### ISSUE TITLE
what is the difference ?

### ISSUE THREAD

**Issue by iloveaman** [amitshekhariitbhu/GlideBitmapPool#1]
what is the difference between you package com.glidebitmappool.internal.*  and Glide's package com.bumptech.glide.load.engine.bitmap_recycle.* ? except Util.java

**Comment by amitshekhariitbhu** [comment]
it's almost same. From there only I  created it for my use-cases and  added few things to handle different android versions. That's why it's name is Glide Bitmap Pool.

**Comment by iloveaman** [comment]
so com.glidebitmappool.internal.*  can be  remove and use glide‘s instead .

**Comment by amitshekhariitbhu** [comment]
I am not using Glide.

**Comment by amitshekhariitbhu** [comment]
Yes you are free to remove it as per your requirement

**Comment by iloveaman** [comment]
thanks , in my opinion , using glide's is a good chooice , in situation below: 
`public class GlideConfiguration implements GlideModule {

    @Override
    public void applyOptions(Context context, GlideBuilder builder) {
        // Apply options to the builder here.
        builder.setDiskCache(new InternalCacheDiskCacheFactory(context, 10 * 1024));//设置使用InternalCacheDiskCacheFactory磁盘高速缓存的大小
        //builder.setDiskCache(new InternalCacheDiskCacheFactory(context, cacheDirectoryName, yourSizeInBytes));//设置磁盘高速缓存的位置
        //builder.setDiskCache(new ExternalCacheDiskCacheFactory(context, cacheDirectoryName, yourSizeInBytes));//缓存在sd卡上公共缓存目录
        builder.setMemoryCache(new LruResourceCache(10 * 1024));//设置大小和/或实现你希望使用内存缓存
        //builder.setBitmapPool(new LruBitmapPool(10 * 1024));
        //统一本地图片和网络图片的BitmapPool
        builder.setBitmapPool(GlideBitmapPool.getInstance().getBitmapPool());
        builder.setDecodeFormat(DecodeFormat.PREFER_RGB_565);
    }

    @Override
    public void registerComponents(Context context, Glide glide) {
        // register ModelLoaders here.
    }
}`

**Comment by amitshekhariitbhu** [comment]
Yes, you are correct. But my use case was different . so I used Fresco Library.

**Comment by iloveaman** [comment]
thanks !

**Comment by amitshekhariitbhu** [comment]
You are welcome
