### ISSUE TITLE
have a bug

### ISSUE THREAD

**Issue by yiyinying** [amitshekhariitbhu/GlideBitmapPool#2]
android 4.2.2
@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (resultCode == Activity.RESULT_OK) {
      Uri imageFileUri=data.getData();
      Display currentDisplay=getWindowManager().getDefaultDisplay();
      int dw=currentDisplay.getWidth();
      int dh = currentDisplay.getHeight()/2-100;
      try {
        //Bitmap bmp = BitmapFactory.decodeStream(getContentResolver().openInputStream(imageFileUri));
        Bitmap bmp = GlideBitmapFactory.decodeStream(
            getContentResolver().openInputStream(imageFileUri),200,200);
        chosenImageView.setImageBitmap(bmp);
      } catch (FileNotFoundException e) {
        e.printStackTrace();
      }
    }
  }
bmp is null.

**Comment by amitshekhariitbhu** [comment]
@yiyinying I will check the issue. Thanks for pointing it out.

Thanks 
Amit Shekhar
